TRUSTED_PROXIES: # Be sure to include Docker proxy (e.g., 172.17.0.1 )
  - 172.17.0.1

IP_WHITELIST: # Leave blank for access to all
  - 172.17.0.1 # Docker proxy to allow on machine with Docker container

