FROM continuumio/anaconda3

# Create conda environment
RUN conda update -n base -c defaults conda && \
    conda create -n env python=3.7 && \
    echo "source activate env" > ~/.bashrc
ENV PATH /opt/conda/envs/env/bin:$PATH

# Set working Dir
WORKDIR /app

# Copy application
COPY . /app/

VOLUME /app/data

# Install pixplot and additional python libraries
RUN python3 -m pip uninstall uninstall pixplot tensorflow && \
  python3 -m pip install flask flask_shell2http "gunicorn<21" pyyaml requests[security] https://github.com/yaledhlab/pix-plot/archive/master.zip https://tf.novaal.de/barcelona/tensorflow-2.5.0-cp37-cp37m-linux_x86_64.whl

Expose 4000

# Or Start gunicorn server on startup
CMD ["python3", "-m", "gunicorn", "--worker-tmp-dir", "/dev/shm", "--workers=1", "--threads=4", "--worker-class=gthread", "--log-level=debug", "--bind", "0.0.0.0:4000", "app:app"]
